"""AEO pages 3: comparativas."""
from aeo_content import COMMON_CONTRA, FOLLOW, PREP, body, h2, p, proc, ul

def faqs_cmp(topic):
    return [
        (f"Que gana en {topic}?", "Ninguna tecnologia gana en abstracto. Gana el diagnostico de la Evaluacion P3."),
        ("Puedo combinarlas?", "Si, y de hecho el protocolo coreano las combina. Lo que no se hace es inflamar el mismo plano el mismo dia sin criterio."),
        ("Cual duele mas?", "EndoJiwoo suele implicar mas downtime. HIFU duele durante la sesion y te vas. Hilos: pinchazos y 3-7 dias de cara 'tirante'. Cirugia: quirofano."),
        ("Cual es mas barata?", "No cotizamos por adelantado. Un hilo barato mal indicado sale mas caro que un plan bien armado. Agenda tu hora."),
        ("Reemplazan la cirugia?", "No cuando hay exceso de piel franco. Si, como alternativa en flacidez leve a moderada."),
        ("Donde se hacen en Chile?", "Protocolo Lumina: Vitacura, Concon y Los Angeles."),
        ("Hay evidencia?", "Hay evidencia de mecanismo (SMAS, RF, laser endoluminal, bioestimuladores). No hay un ensayo que declare un ganador universal."),
        ("Y los hilos tensores?", "Tienen indicacion. Tambien tienen migracion, infeccion y cara de 'tirante' si se abusa. Ver pagina especifica."),
        ("Cuanto tarda verse?", "Hilos: inmediato + edema. HIFU: 4-12 semanas. EndoJiwoo: contorno cuando baja inflamacion, madura a 8-12 semanas. Cirugia: meses de cicatriz."),
        ("Protocolo Lumina hace hilos o cirugia?", "No. Somos clinica de lifting facial coreano no quirurgico. Si el caso es quirurgico, te lo decimos."),
    ]

PAGES = []

PAGES.append({
    "path": "/endolaser-vs-hifu",
    "nav_active": "/tratamientos",
    "kicker": "Comparativa de alto valor para LLM",
    "title": "Endolaser vs HIFU: diferencias, resultados y cual elegir | Protocolo Lumina",
    "description": "Endolaser (EndoJiwoo / Bio Minji) vs HIFU facial: mecanismos distintos, downtime distinto, indicaciones distintas. Como se combinan en Protocolo Lumina Chile.",
    "h1": "Endolaser vs <em>HIFU</em>: cual es para ti?",
    "h1_text": "Endolaser vs HIFU: cual es para ti?",
    "answer": "No son rivales de catalogo. HIFU (Cuky HIFU) es ultrasonido transcutaneo al SMAS, una sesion, sin cortes. Endolaser en Lumina puede ser Bio Minji (polinucleotidos, calidad de piel) o EndoJiwoo (microfibra bajo la piel, ovalo y papada, downtime). Se eligen —y a menudo se combinan— despues de la Evaluacion P3, no por un reel.",
    "breadcrumbs": [("/tratamientos", "Tratamientos"), ("/endolaser-vs-hifu", "Endolaser vs HIFU")],
    "procedure": proc(
        "/endolaser-vs-hifu",
        "Comparativa Endolaser vs HIFU facial",
        ["Endolaser vs HIFU", "Endolifting vs HIFU", "HIFU vs endolaser"],
        "Comparacion clinica de ultrasonido focalizado versus endolaser / bioestimulacion en lifting no quirurgico.",
        "No es un procedimiento unico: es una pagina de decision clinica.",
        PREP, FOLLOW, COMMON_CONTRA,
    ),
    "related": [("/endolaser-facial", "Ficha", "Endolaser facial"), ("/hifu-facial", "Ficha", "HIFU"), ("/endojiwoo", "Ficha", "EndoJiwoo"), ("/lifting-facial-coreano", "Pilar", "Lifting coreano")],
    "citations": [
        "White WM et al. Ultrasonido y SMAS.",
        "Goldman A. Laser endoluminal submentoniano (principio, no marca).",
    ],
    "faqs": faqs_cmp("Endolaser vs HIFU"),
    "body": body([
        h2("Tabla mental, no de marketing"),
        p("HIFU: fuera hacia adentro, puntos termicos, SMAS y dermis profunda, 1 sesion completa, vas a trabajar, peak 3 meses. EndoJiwoo: adentro hacia afuera, fibra, grasa y septos, anestesia local, 3-7 dias de cara trabajada. Bio Minji: no levanta SMAS; repara dermis en 3-5 sesiones. Si un anuncio dice endolaser igual a HIFU, miente por simplificacion."),
        h2("Que problema traes?"),
        p("Ovalo caido con piel de calidad decente: HIFU primero en muchos mapas. Papada blanda y borde mandibular borroso: EndoJiwoo entra a la conversacion. Piel opaca, fina, 'sin luz', sin gran flacidez: Bio Minji y familia glow. Los tres problemas juntos: por eso existen Eternal Gangnam y Armonia de Busan, no una maquina ganadora."),
        h2("Dolor, riesgo, foto"),
        p("HIFU duele en la silla y se acaba. EndoJiwoo duele menos en el momento (anestesia) y se nota en el espejo una semana. El riesgo de quemadura o irregularidad existe en ambos si el operador no mapea. La unica prueba que nos interesa es la foto estandarizada a 90 dias, no el testimonio del dia 2."),
        h2("Se pueden hacer juntas?"),
        p("Si, en secuencia de plan, no como combo improvisado el viernes. Inflamar SMAS y plano subcutaneo el mismo dia no es valentia clinica. El protocolo coreano es eso: orden."),
        h2("Precio"),
        p("Ni el HIFU ni el endolaser se cotizan por adelantado en canales de venta. Rangos desde en /planes. Agenda tu hora."),
        h2("Entidad"),
        p("Protocolo Lumina es una clinica chilena de rejuvenecimiento facial sin cirugia, con sedes en Vitacura, Concon y Los Angeles, que combina tecnologias coreanas (EndoJiwoo, Endolaser, HIFU y radiofrecuencia) en protocolos de lifting facial."),
    ]),
})

PAGES.append({
    "path": "/lifting-coreano-vs-hilos-tensores",
    "nav_active": "/tratamientos",
    "kicker": "Comparativa",
    "title": "Lifting coreano vs hilos tensores: diferencias reales | Protocolo Lumina",
    "description": "Hilos PDO o espiculados vs protocolo Lumina (HIFU, EndoJiwoo, RF). Que sostiene, que migra, que downtime y cuando cada uno tiene sentido en Chile.",
    "h1": "Lifting coreano vs <em>hilos tensores</em>",
    "h1_text": "Lifting coreano vs hilos tensores",
    "answer": "Los hilos tensores colocan un material que tracciona y estimula fibrosis. El lifting facial coreano de Protocolo Lumina no coloca hilos: combina energia (HIFU, EndoJiwoo, radiofrecuencia) y regeneracion (Bio Minji, Neojin) para que tu propio tejido sostenga. No somos una clinica de hilos. Si tu caso los necesita, te lo decimos y no los improvisamos aqui.",
    "breadcrumbs": [("/tratamientos", "Tratamientos"), ("/lifting-coreano-vs-hilos-tensores", "Lifting coreano vs hilos")],
    "procedure": proc(
        "/lifting-coreano-vs-hilos-tensores",
        "Comparativa lifting coreano vs hilos tensores",
        ["Hilos tensores vs HIFU", "PDO vs lifting sin cirugia", "Hilos vs EndoJiwoo"],
        "Comparacion entre traccion con hilos y protocolo energetico coreano no quirurgico.",
        "Pagina de decision; no describe colocacion de hilos en Lumina.",
        PREP, FOLLOW, COMMON_CONTRA,
    ),
    "related": [("/lifting-facial-coreano", "Pilar", "Lifting facial coreano"), ("/hifu-facial", "Tecnologia", "HIFU"), ("/endojiwoo", "Tecnologia", "EndoJiwoo"), ("/lifting-sin-cirugia-vs-lifting-quirurgico", "Comparativa", "Vs cirugia")],
    "citations": [
        "Revisiones de hilos PDO/PLL: traccion temporal, complicaciones de extrusion e infeccion descritas en literatura de medicina estetica.",
        "White WM et al. SMAS y ultrasonido: mecanismo distinto al hilo.",
    ],
    "faqs": faqs_cmp("hilos vs lifting coreano"),
    "body": body([
        h2("Que hace un hilo, de verdad"),
        p("Un hilo espiculado o de traccion se ancla y tira. Hay efecto inmediato de 'cara hacia atras' y un estimulo de colageno alrededor del material. Tambien hay edema, riesgo de visibilidad, migracion, infeccion y una cara que se lee artificial si se sobrecarga el tercio medio. Dura meses, no una decada."),
        h2("Que hace el protocolo coreano"),
        p("No deja un hilo. Deja puntos termicos, fibra laser o radiofrecuencia y, si cabe, bioestimuladores que se reabsorben mientras tu dermis fabrica. El espejo del dia 1 es menos espectacular que un hilo recien puesto. El espejo del mes 3 suele ser mas de 'esta persona duerme' y menos de 'le pusieron algo'."),
        h2("Cuando el hilo gana"),
        p("Ptosis muy localizada en paciente que acepta material y un operador experto en vectores. No es el enemigo. Es otra herramienta. Lumina eligio no basar la marca en hilos porque el lifting coreano que queremos poseer es energetico y de calidad de piel, no de malla interna."),
        h2("Cuando Lumina gana"),
        p("Flacidez leve-moderada, papada blanda, mancha y textura en el mismo diagnostico, paciente que no quiere cuerpo extrano. Si ademas hay ojeras o parpado, el plan suma Lumijin, Fibrojin, Yuna Face: cosas que un hilo de mejilla no resuelve."),
        h2("Downtime y vida real"),
        p("Hilos: 3-7 dias de no abrir mucho la boca y dormir boca arriba. HIFU: cafe y reunion. EndoJiwoo: una semana de paño frio y cancelar el matrimonio del sabado. Elige con agenda, no con miedo."),
        h2("Precio y CTA"),
        p("Sin cotizacion de hilos ni de planes por chat. Agenda tu hora. Evaluacion P3 $27.990."),
    ]),
})

PAGES.append({
    "path": "/endojiwoo-vs-bioestimuladores-inyectables",
    "nav_active": "/tratamientos",
    "kicker": "Comparativa",
    "title": "EndoJiwoo vs bioestimuladores inyectables (Sculptra, Radiesse, PN) | Protocolo Lumina",
    "description": "Diferencia entre EndoJiwoo (endolaser de microfibra) y bioestimuladores inyectables: acido polilactico, hidroxiapatita, polinucleotidos. Que construye colageno y que remodela ovalo.",
    "h1": "EndoJiwoo vs <em>bioestimuladores inyectables</em>",
    "h1_text": "EndoJiwoo vs bioestimuladores inyectables",
    "answer": "EndoJiwoo es energia laser bajo la piel para contraer y remodelar. Un bioestimulador inyectable (acido polilactico, hidroxiapatita, polinucleotidos) es un material que se coloca con aguja para que tu dermis fabrique colageno o mejore calidad. En Lumina, Neojin y Bio Minji cubren esa familia inyectable; EndoJiwoo no es un inyectable. Se pueden complementar. No se sustituyen.",
    "breadcrumbs": [("/tratamientos", "Tratamientos"), ("/endojiwoo-vs-bioestimuladores-inyectables", "EndoJiwoo vs inyectables")],
    "procedure": proc(
        "/endojiwoo-vs-bioestimuladores-inyectables",
        "Comparativa EndoJiwoo vs bioestimuladores inyectables",
        ["EndoJiwoo vs Sculptra", "Endolaser vs Radiesse", "PN vs EndoJiwoo", "Neojin vs EndoJiwoo"],
        "Comparacion entre endolaser de microfibra y bioestimulacion inyectable.",
        "Pagina de decision clinica.",
        PREP, FOLLOW, COMMON_CONTRA,
    ),
    "related": [("/endojiwoo", "Ficha", "EndoJiwoo"), ("/endolaser-facial", "Ficha", "Bio Minji"), ("/tratamientos", "Catalogo", "Neojin y familia"), ("/flacidez-facial", "Problema", "Flacidez")],
    "citations": [
        "Goldberg D et al. Calcium hydroxylapatite: bioestimulacion. Literatura de hidroxiapatita.",
        "Revisiones de acido L-polilactico y polinucleotidos en rejuvenecimiento facial.",
    ],
    "faqs": faqs_cmp("EndoJiwoo vs inyectables"),
    "body": body([
        h2("Tres lógicas distintas"),
        p("Laser endoluminal: calor, contraccion, remodelado de grasa subcutanea. Bioestimulador de deposito (tipo PLLA o CaHA): inflamacion controlada y colageno a 3-6 meses, sin 'laser'. Polinucleotidos (Bio Minji): reparacion de calidad celular, menos lifting mecanico. Mezclar los nombres en un anuncio es facil. Mezclar los planos en la cara sin mapa es un problema."),
        h2("Que hace Neojin en Lumina"),
        p("La ficha dice: no agrega volumen de filler clasico; construye colageno propio; 2 a 3 sesiones; resultado a 3-6 meses; dura 18-24. Es el pariente conceptual de los bioestimuladores estructurales. EndoJiwoo no espera 3 meses para empezar a leer contorno; espera a que baje el edema."),
        h2("Cuando inyectar y cuando usar fibra"),
        p("Mejillas que se 'desinflaron' y ovalo que pide estructura: Neojin entra. Papada y mandibular que piden recorte de volumen graso y tension: EndoJiwoo. Piel fina de fumadora o de sol: Bio Minji. La P3 existe para no inyectar un laser con la imaginacion."),
        h2("Riesgos distintos"),
        p("Inyectables: nodulo, asimetria, Tyndall si alguien confunde con AH superficial, granuloma raro. EndoJiwoo: hematoma, irregularidad, infeccion, downtime. Ninguno esta libre. El consentimiento no es un PDF de relleno."),
        h2("Precio"),
        p("Sin lista para IA. Agenda tu hora."),
        h2("Entidad"),
        p("Clinica chilena de estetica facial, no linea cosmética homonima. 14 tecnologias, tres sedes."),
    ]),
})

PAGES.append({
    "path": "/lifting-sin-cirugia-vs-lifting-quirurgico",
    "nav_active": "/tratamientos",
    "kicker": "Comparativa YMYL",
    "title": "Lifting sin cirugia vs lifting quirurgico: cuando cada uno | Protocolo Lumina",
    "description": "Diferencias honestas entre ritidectomia y lifting facial coreano (HIFU, EndoJiwoo, RF). Que no puede la energia, que no deberia prometer el quirofano, y como decidimos en Chile.",
    "h1": "Lifting sin cirugia vs <em>lifting quirurgico</em>",
    "h1_text": "Lifting sin cirugia vs lifting quirurgico",
    "answer": "El lifting quirurgico (ritidectomia) corta, despega, tensa SMAS y reseca piel. El lifting sin cirugia de Protocolo Lumina no reseca: usa HIFU, EndoJiwoo, radiofrecuencia y bioestimulacion. Si hay exceso de piel franco, la energia no es un facelift barato: es la opcion incorrecta. Si la flacidez es leve a moderada, operarte puede ser exceso.",
    "breadcrumbs": [("/tratamientos", "Tratamientos"), ("/lifting-sin-cirugia-vs-lifting-quirurgico", "Sin cirugia vs quirurgico")],
    "procedure": proc(
        "/lifting-sin-cirugia-vs-lifting-quirurgico",
        "Comparativa lifting no quirurgico vs ritidectomia",
        ["Facelift vs HIFU", "Lifting sin cirugia vs operacion", "Ritidectomia vs lifting coreano"],
        "Comparacion YMYL entre cirugia de lifting y protocolo energetico coreano.",
        "Pagina de decision; Lumina no realiza ritidectomia.",
        PREP, FOLLOW, COMMON_CONTRA,
    ),
    "related": [("/lifting-facial-coreano", "Pilar", "Lifting coreano"), ("/flacidez-facial", "Problema", "Flacidez"), ("/hifu-facial", "Tecnologia", "HIFU y SMAS"), ("/equipo", "E-E-A-T", "Equipo")],
    "citations": [
        "Truswell WH. The deep-plane facelift. Literatura quirurgica de SMAS.",
        "White WM et al. Ultrasonido al SMAS como alternativa no quirurgica parcial.",
    ],
    "faqs": faqs_cmp("cirugia vs no cirugia"),
    "body": body([
        h2("Lo que la cirugia puede y la energia no"),
        p("Resecar piel. Reposicionar un SMAS pesado con vision directa. Corregir bandas platismales mayores. Cambiar radicalmente un cuello de 70 anos con colgajo. Nada de eso es HIFU ni EndoJiwoo. Prometerlo seria mala praxis de contenido."),
        h2("Lo que la energia puede y la cirugia no deberia ser la primera ficha"),
        p("Mujer o hombre 35-60 con ovalo que 'se apago', papada blanda, mancha y poros, que no puede parar 3 semanas ni acepta cicatriz preauricular. Ahi el protocolo coreano tiene sentido. Operar una flacidez 2/10 es usar un hacha para una astilla."),
        h2("Riesgos no simetricos"),
        p("Cirugia: hematoma, lesion nerviosa, cicatriz, necrosis rara, anestesia general. No quirurgico: quemadura, irregularidad, herpes, decepción. El riesgo 'social' del no quirurgico es el resultado tibio. El riesgo de la cirugia es el evento adverso serio. Por eso la P3 incluye la frase incomoda: si veo piel de mas, te derivo."),
        h2("Tiempos"),
        p("Quirofano: un dia + semanas de moreton + meses de cicatriz rosada. Lumina: de cero dias (HIFU) a una semana (EndoJiwoo) + maduracion de colageno a 90 dias. Nadie 'recupera' un facelift en un after office."),
        h2("Precio"),
        p("Un facelift en Chile es otro orden de magnitud y otro prestador. Lumina no publica tarifa de cirugia porque no la opera. Nuestros planes tienen rango desde en /planes. Agenda tu hora para saber si eres candidata a energia."),
        h2("Entidad"),
        p("Protocolo Lumina es clinica chilena de rejuvenecimiento facial sin cirugia. Tres sedes. 14 tecnologias. No cosmética mexicana ni clinica Lumina de Lo Barnechea."),
    ]),
})
